/**
 * WP-D04 adversarial corpus for contribution-association evidence.
 *
 * Every case is synthetic: no real capture, commit, or credential appears here.
 * Expected values record what the CURRENT engine must do (association-only,
 * conservative, withhold rather than inflate) — they are not endorsements that
 * this is the only defensible answer. Categories are descriptive, not a truth
 * taxonomy. Nothing in this corpus may be cited as authorship, quality,
 * outcome, or value evidence; association-only, never authorship.
 */

import type {
  ContributionArtifact,
  ContributionCandidatesInput,
  ContributionEvidenceMethod,
  ContributionEvidenceStatus,
  ContributionOpaqueFile,
  ContributionTextFile,
  ContributionAssessmentInput,
} from '../../src/git/contribution.ts';


export const CONTRIBUTION_CORPUS_VERSION = 'wp-d04-corpus/1';

export interface ContributionCorpusCase {
  readonly id: string;
  readonly provenance: 'synthetic';
  readonly title: string;
  readonly rationale: string;
  readonly categories: readonly string[];
  readonly expected: { readonly status: ContributionEvidenceStatus; readonly method: ContributionEvidenceMethod };
  readonly input: ContributionAssessmentInput | ContributionCandidatesInput;
  readonly nonClaims: readonly string[];
  readonly limitations: readonly string[];
}

type MutableArtifact = {
  -readonly [K in keyof ContributionArtifact]: ContributionArtifact[K];
};

type MutableTextFile = {
  -readonly [K in keyof ContributionTextFile]: ContributionTextFile[K];
};

type MutableOpaqueFile = {
  -readonly [K in keyof ContributionOpaqueFile]: ContributionOpaqueFile[K];
};

type MutableFile = MutableTextFile | MutableOpaqueFile;

function textFile(path: string, addedLines: string[], extra: Partial<MutableTextFile> = {}): MutableFile {
  return { path, kind: 'text', addedLines, ...extra };
}

function opaqueFile(path: string, kind: 'generated' | 'binary' | 'unsupported'): MutableFile {
  return { path, kind };
}

function artifactOf(id: string, sourceId: string, files: MutableFile[], patchIdentity: string | null = null): MutableArtifact {
  return { id, sourceId, files, patchIdentity };
}

function assessPair(
  id: string,
  title: string,
  rationale: string,
  categories: string[],
  expected: { status: ContributionEvidenceStatus; method: ContributionEvidenceMethod },
  source: MutableArtifact,
  target: MutableArtifact,
  temporal?: ContributionAssessmentInput['temporal'],
): ContributionCorpusCase {
  return {
    id,
    provenance: 'synthetic',
    title,
    rationale,
    categories,
    expected,
    input: temporal === undefined ? { source, target } : { source, target, temporal },
    nonClaims: ['ai_authorship', 'outcome_success', 'code_quality', 'realized_value'],
    limitations: [
      'Synthetic association evidence: verifies what the current engine does, not what a better engine should do.',
      'Baseline scores are diagnostic comparisons, not ground truth, thresholds, or value evidence.',
    ],
  };
}

function candidatesCase(
  id: string,
  title: string,
  rationale: string,
  categories: string[],
  expected: { status: ContributionEvidenceStatus; method: ContributionEvidenceMethod },
  input: ContributionCandidatesInput,
): ContributionCorpusCase {
  const base = assessPair(id, title, rationale, categories, expected, artifactOf('unused', 'unused', []), artifactOf('unused', 'unused', []));
  return { ...base, input };
}

const BASE_MS = 1_700_000_000_000;

function withinWindow(): ContributionAssessmentInput['temporal'] {
  return {
    sourceObservedAtMs: BASE_MS + 1_000,
    targetObservedAtMs: BASE_MS + 5_000,
    windowStartMs: BASE_MS,
    windowEndMs: BASE_MS + 10_000,
  };
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object') {
    for (const item of Object.values(value)) deepFreeze(item);
    Object.freeze(value);
  }
  return value;
}

const CORE_CORPUS: readonly ContributionCorpusCase[] = deepFreeze([
  assessPair(
    'c001-exact-patch-identity',
    'Exact patch identity on a same-path text change',
    'Collector-supplied patch identity is the strongest declared evidence; contents are never reinterpreted.',
    ['exact', 'same-path', 'text', 'clean-capture'],
    { status: 'exact', method: 'exact_patch_identity' },
    artifactOf('p-c001', 'proxy:model-a', [textFile('src/app.ts', ['const answer = 42;', 'export default answer;'])], 'patch:identity-c001'),
    artifactOf('k-c001', 'git:commit', [textFile('src/app.ts', ['const answer = 42;', 'export default answer;'])], 'patch:identity-c001'),
  ),
  assessPair(
    'c002-generated-lineage',
    'Generated output linked by explicit generator lineage',
    'Generated bytes are never text-compared; only explicit lineage identity can carry generated evidence.',
    ['exact', 'generated', 'lineage', 'clean-capture'],
    { status: 'exact', method: 'generated_lineage' },
    { ...artifactOf('p-c002', 'proxy:model-a', [opaqueFile('dist/bundle.js', 'generated')]), generationIdentity: 'gen:app:v1:c002' },
    { ...artifactOf('k-c002', 'git:commit', [opaqueFile('dist/bundle.js', 'generated')]), generationIdentity: 'gen:app:v1:c002' },
    withinWindow(),
  ),
  assessPair(
    'c003-hunk-identity-structural',
    'Matching hunk identity on the declared path relationship',
    'Collector hunk identity is structural evidence below exact patch identity and above raw text overlap.',
    ['structural', 'same-path', 'text', 'collector-metadata'],
    { status: 'structural', method: 'hunk_similarity' },
    artifactOf('p-c003', 'proxy:model-a', [textFile('src/util.ts', ['export function sum(a: number, b: number): number { return a + b; }'], { hunkIdentity: 'hunk:c003' })]),
    artifactOf('k-c003', 'git:commit', [textFile('src/util.ts', ['export function sum(a: number, b: number): number { return a + b; }'], { hunkIdentity: 'hunk:c003' })]),
  ),
  assessPair(
    'c004-ast-fingerprint-rewrite',
    'AST fingerprints survive a variable-keyword rewrite',
    'Same-language AST fingerprints associate code whose raw lines differ (`const` vs `let`), a case pure text overlap misses.',
    ['structural', 'same-path', 'rewrite', 'ast', 'collector-metadata'],
    { status: 'structural', method: 'structural_ast_similarity' },
    artifactOf('p-c004', 'proxy:model-a', [textFile('src/sum.ts', ['const total = add(parts);'], { language: 'typescript', structuralFingerprint: 'ast:c004:call-add' })]),
    artifactOf('k-c004', 'git:commit', [textFile('src/sum.ts', ['let total = add(parts);'], { language: 'typescript', structuralFingerprint: 'ast:c004:call-add' })]),
  ),
  assessPair(
    'c005-same-path-text-overlap',
    'Unique same-path text overlap at full retention',
    'With one source file, one target file, and identical normalized lines, unique structural overlap is the declared fallback.',
    ['structural', 'same-path', 'text', 'clean-capture'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c005', 'proxy:model-a', [textFile('src/hello.ts', ['export function greet(name: string): string {', '  return `hello ${name}`;', '}'])]),
    artifactOf('k-c005', 'git:commit', [textFile('src/hello.ts', ['export function greet(name: string): string {', '  return `hello ${name}`;', '}'])]),
  ),
  assessPair(
    'c006-partial-retention-overlap',
    'Proposed lines partially retained by later human edits',
    'Two of three lines survive, but a majority alone does not meet the declared 0.75 Dice floor; association remains unresolved.',
    ['unresolved', 'same-path', 'human-edit', 'partial-retention', 'competing-edit'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c006', 'proxy:model-a', [textFile('src/auth.ts', [
      'export function signIn(user: string): boolean {',
      '  return user.length > 0;',
      '}',
    ])]),
    artifactOf('k-c006', 'git:commit', [textFile('src/auth.ts', [
      'export function signIn(user: string): boolean {',
      '  return user.length > 0 && !user.includes(" ");',
      '}',
    ])]),
  ),
  assessPair(
    'c007-rename-with-metadata',
    'Move to a new path declared through target previousPath',
    'A declared rename lets the engine pair the files; the relation is renamed_or_moved, never same-path, never exact.',
    ['structural', 'rename', 'path-relation', 'move'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c007', 'proxy:model-a', [textFile('src/old/location.ts', ['export const moved = true;'])]),
    artifactOf('k-c007', 'git:commit', [textFile('src/new/location.ts', ['export const moved = true;'], { previousPath: 'src/old/location.ts' })]),
  ),
  assessPair(
    'c008-move-source-declared',
    'Move declared on the source side via previousPath',
    'The engine accepts the declared relation from either side; direction of declaration does not change the verdict.',
    ['structural', 'rename', 'path-relation', 'move'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c008', 'proxy:model-a', [textFile('src/new/location.ts', ['export const moved = true;'], { previousPath: 'src/old/location.ts' })]),
    artifactOf('k-c008', 'git:commit', [textFile('src/old/location.ts', ['export const moved = true;'])]),
  ),
  assessPair(
    'c009-pathless-fenced-block',
    'Pathless proposal block meeting committed content',
    'An empty path is missing identity; an empty previousPath cannot supply a file relationship.',
    ['unresolved', 'pathless', 'text', 'weaker-identity'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c009', 'proxy:model-a', [textFile('', ['export function parse(input: string): number {', '  return Number(input);', '}'])]),
    artifactOf('k-c009', 'git:commit', [textFile('src/parse.ts', ['export function parse(input: string): number {', '  return Number(input);', '}'], { previousPath: '' })]),
  ),
  assessPair(
    'c010-wrong-file-pathless-unmatched',
    'Pathless proposal with no declared path relationship',
    'Without a declared path relation there is no pairing candidate; identical content cannot invent one.',
    ['unresolved', 'pathless', 'wrong-file', 'no-relation'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c010', 'proxy:model-a', [textFile('', ['export function unrelated(): void {}'])]),
    artifactOf('k-c010', 'git:commit', [textFile('src/other.ts', ['export function unrelated(): void {}'])]),
  ),
  assessPair(
    'c011-wrong-file-same-lines',
    'Proposal targeting file A, commit changes file B',
    'Same lines under different paths with no declared rename relation must not be treated as the same file identity.',
    ['unresolved', 'wrong-file', 'no-relation', 'file-identity'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c011', 'proxy:model-a', [textFile('src/config.ts', ['export const retries = 3;'])]),
    artifactOf('k-c011', 'git:commit', [textFile('src/settings.ts', ['export const retries = 3;'])]),
  ),
  assessPair(
    'c012-move-without-metadata',
    'Committed move with no previousPath metadata',
    'A real move whose collector dropped rename metadata looks like unrelated paths; the engine withholds rather than guessing.',
    ['unresolved', 'rename', 'move', 'missing-metadata', 'file-identity'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c012', 'proxy:model-a', [textFile('src/legacy/handler.ts', ['export function handle(req: string): string {', '  return req.trim();', '}'])]),
    artifactOf('k-c012', 'git:commit', [textFile('src/api/handler.ts', ['export function handle(req: string): string {', '  return req.trim();', '}'])]),
  ),
  assessPair(
    'c013-semantic-rewrite-below-threshold',
    'Semantic rewrite that reorders and renames most lines',
    'A heavy rewrite keeps the function name but replaces nearly every line; below the similarity floor it must stay unresolved.',
    ['unresolved', 'rewrite', 'structural-rewrite', 'human-edit'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c013', 'proxy:model-a', [textFile('src/report.ts', [
      'export function renderReport(rows: string[]): string {',
      '  let out = "";',
      '  for (const row of rows) out += row + ";";',
      '  return out;',
      '}',
    ])]),
    artifactOf('k-c013', 'git:commit', [textFile('src/report.ts', [
      'export function renderReport(entries: readonly string[]): string {',
      '  const joined = entries.join("|");',
      '  return `<report>${joined}</report>`;',
      '}',
    ])]),
  ),
  assessPair(
    'c014-boilerplate-confounder',
    'Import line match declared as copied boilerplate',
    'A declared copied_boilerplate confounder withholds the unique match rather than laundering shared imports.',
    ['unresolved', 'confounder', 'boilerplate', 'competing-edit'],
    { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf('p-c014', 'proxy:model-a', [textFile('src/app.ts', ['import { strict as assert } from "node:assert";'])]), confounders: ['copied_boilerplate'] },
    artifactOf('k-c014', 'git:commit', [textFile('src/app.ts', ['import { strict as assert } from "node:assert";'])]),
  ),
  assessPair(
    'c015-formatting-only-confounder',
    'Whitespace-only restyle declared as formatting confounder',
    'A formatting_only confounder keeps a whitespace-only match unresolved even though normalized text would score 1.',
    ['unresolved', 'confounder', 'formatting', 'rewrite'],
    { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf('p-c015', 'proxy:model-a', [textFile('src/style.ts', ['export const margin = 12;'])]), confounders: ['formatting_only'] },
    artifactOf('k-c015', 'git:commit', [textFile('src/style.ts', ['export   const   margin   =   12;'])]),
  ),
  assessPair(
    'c016-generated-without-lineage',
    'Generated file pair with no generator lineage declared',
    'Generated content without lineage must never be text-compared, even at identical paths and inside a valid window.',
    ['unresolved', 'generated', 'confounder', 'no-lineage'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c016', 'proxy:model-a', [opaqueFile('dist/bundle.js', 'generated')]),
    artifactOf('k-c016', 'git:commit', [opaqueFile('dist/bundle.js', 'generated')]),
    withinWindow(),
  ),
  assessPair(
    'c017-partial-capture-confounder',
    'Truncated proposal capture meeting a real commit',
    'partial_capture is declared by the collector for truncated captures; the match is retained but stays unresolved.',
    ['unresolved', 'confounder', 'partial-capture', 'missing-data'],
    { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf('p-c017', 'proxy:model-a', [textFile('src/long.ts', ['export const alpha = 1;', 'export const beta = 2;'])]), confounders: ['partial_capture'] },
    artifactOf('k-c017', 'git:commit', [textFile('src/long.ts', ['export const alpha = 1;', 'export const beta = 2;'])]),
  ),
  assessPair(
    'c018-human-edit-confounder',
    'Concurrent human edit declared alongside a real match',
    'A concurrent_human_edit confounder forces unresolved even though every line overlaps.',
    ['unresolved', 'confounder', 'human-edit', 'competing-edit'],
    { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf('p-c018', 'proxy:model-a', [textFile('src/feature.ts', ['feature();'])]), confounders: ['concurrent_human_edit'] },
    artifactOf('k-c018', 'git:commit', [textFile('src/feature.ts', ['feature();'])]),
  ),
  assessPair(
    'c019-revert-reapply-confounder',
    'Revert-and-reapply cycle declared as a confounder',
    'revert_reapply breaks retention ordering assumptions, so even a perfect text match stays unresolved.',
    ['unresolved', 'confounder', 'revert', 'temporal-trap'],
    { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf('p-c019', 'proxy:model-a', [textFile('src/patched.ts', ['patch();'])]), confounders: ['revert_reapply'] },
    artifactOf('k-c019', 'git:commit', [textFile('src/patched.ts', ['patch();'])]),
  ),
  assessPair(
    'c020-temporal-window-only',
    'Opaque content linked only through a valid temporal window',
    'When no content can be compared, an explicit window with strict ordering is the declared floor: temporal, not structural.',
    ['temporal', 'window', 'binary', 'clean-capture'],
    { status: 'temporal', method: 'temporal_association' },
    artifactOf('p-c020', 'proxy:model-a', [opaqueFile('assets/logo.png', 'binary')]),
    artifactOf('k-c020', 'git:commit', [opaqueFile('assets/logo.png', 'binary')]),
    withinWindow(),
  ),
  assessPair(
    'c021-temporal-outside-window',
    'Source observed before the window opens',
    'A source outside the half-open window has no temporal association even though it strictly precedes the target.',
    ['temporal', 'window', 'out-of-bounds', 'binary'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c021', 'proxy:model-a', [opaqueFile('assets/logo.png', 'binary')]),
    artifactOf('k-c021', 'git:commit', [opaqueFile('assets/logo.png', 'binary')]),
    {
      sourceObservedAtMs: BASE_MS - 1_000,
      targetObservedAtMs: BASE_MS + 5_000,
      windowStartMs: BASE_MS,
      windowEndMs: BASE_MS + 10_000,
    },
  ),
  assessPair(
    'c022-temporal-ordering-violation',
    'Target observed before the source inside the window',
    'Non-strict ordering breaks causality of the window; within-window alone must not upgrade the verdict.',
    ['temporal', 'window', 'out-of-bounds', 'ordering'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c022', 'proxy:model-a', [textFile('src/order.ts', ['export const order = "violated";'])]),
    artifactOf('k-c022', 'git:commit', [textFile('src/order.ts', ['export const order = "reversed";'])]),
    {
      sourceObservedAtMs: BASE_MS + 6_000,
      targetObservedAtMs: BASE_MS + 2_000,
      windowStartMs: BASE_MS,
      windowEndMs: BASE_MS + 10_000,
    },
  ),
  candidatesCase(
    'c023-competing-candidate-set',
    'Two candidates in one attribution window',
    'A candidate set is an attribution conflict: multiple_ai_sources is raised and the verdict stays unresolved regardless of content.',
    ['unresolved', 'candidates', 'competing', 'multiple-sources'],
    { status: 'unresolved', method: 'unresolved' },
    {
      target: artifactOf('k-c023', 'git:commit', [textFile('src/plan.ts', ['plan();'])]),
      candidates: [
        { source: artifactOf('p-c023a', 'proxy:model-a', [textFile('src/plan.ts', ['plan-a();'])]), temporal: withinWindow() },
        { source: artifactOf('p-c023b', 'proxy:model-b', [textFile('src/plan.ts', ['plan-b();'])]), temporal: withinWindow() },
      ],
    },
  ),
  assessPair(
    'c024-tied-target-candidates',
    'One source file tied across two committed files',
    'Two qualifying committed targets tie on score; ambiguity must withhold selection rather than pick a row.',
    ['unresolved', 'candidates', 'ambiguity', 'same-path'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c024', 'proxy:model-a', [textFile('src/shared.ts', ['export const shared = "shared";'])]),
    artifactOf('k-c024', 'git:commit', [
      textFile('src/one.ts', ['export const shared = "shared";'], { previousPath: 'src/shared.ts' }),
      textFile('src/two.ts', ['export const shared = "shared";'], { previousPath: 'src/shared.ts' }),
    ]),
  ),
  assessPair(
    'c025-multi-source-unmatched-target',
    'Two proposal files, only one committed',
    'A partial application: the matched file pairs structurally while the dropped file stays unmatched; no exclusion list silences it.',
    ['structural', 'same-path', 'partial-application', 'missing-data'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c025', 'proxy:model-a', [
      textFile('src/kept.ts', ['export const kept = true;']),
      textFile('src/dropped.ts', ['export const dropped = true;']),
    ]),
    artifactOf('k-c025', 'git:commit', [textFile('src/kept.ts', ['export const kept = true;'])]),
  ),
  assessPair(
    'c026-mixed-generated-and-text',
    'Comparable text beside an excluded generated sibling',
    'Excluded opaque content is reported as excluded, not silently dropped; the comparable text still carries the structural verdict.',
    ['structural', 'same-path', 'generated', 'excluded-content'],
    { status: 'structural', method: 'normalized_text_overlap' },
    { ...artifactOf('p-c026', 'proxy:model-a', [textFile('src/api.ts', ['export const api = "v1";']), opaqueFile('dist/api.js', 'generated')]), generationIdentity: null },
    artifactOf('k-c026', 'git:commit', [textFile('src/api.ts', ['export const api = "v1";']), opaqueFile('dist/api.js', 'generated')]),
  ),
  assessPair(
    'c027-no-temporal-context-structural',
    'Structural verdict without any temporal context',
    'Temporal evidence is optional; unique structural overlap stands on its own and never invents ordering.',
    ['structural', 'same-path', 'text', 'no-temporal'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c027', 'proxy:model-a', [textFile('src/plain.ts', ['export const plain = 1;'])]),
    artifactOf('k-c027', 'git:commit', [textFile('src/plain.ts', ['export const plain = 1;'])]),
  ),
  assessPair(
    'c028-patch-identity-mismatch',
    'Different patch identities on identical content',
    'Non-matching patch identities downgrade otherwise-identical content to structural, never exact.',
    ['structural', 'same-path', 'text', 'identity-mismatch'],
    { status: 'structural', method: 'normalized_text_overlap' },
    artifactOf('p-c028', 'proxy:model-a', [textFile('src/same.ts', ['export const same = true;'])], 'patch:alpha'),
    artifactOf('k-c028', 'git:commit', [textFile('src/same.ts', ['export const same = true;'])], 'patch:beta'),
  ),
  assessPair(
    'c029-empty-source-artifact',
    'Empty source with no lines and no identity',
    'Nothing comparable and nothing declared: unresolved is the only honest verdict.',
    ['unresolved', 'missing-data', 'empty', 'no-relation'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c029', 'proxy:model-a', []),
    artifactOf('k-c029', 'git:commit', [textFile('src/empty.ts', ['export const waiting = true;'])]),
  ),
  assessPair(
    'c030-revoked-identity-evidence-removal',
    'Simulated evidence removal of the source artifact',
    'Revoked identity is simulated as evidence removal: an empty source artifact is indistinguishable from no capture, so unresolved is correct and no revocation machinery is exercised.',
    ['unresolved', 'missing-data', 'revoked', 'evidence-removal'],
    { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-c030', 'proxy:model-a', []),
    artifactOf('k-c030', 'git:commit', [textFile('src/deleted.ts', ['export const removed = true;'])]),
  ),
  candidatesCase(
    'c031-empty-candidate-set',
    'Attribution request with zero candidates',
    'An empty candidate set means nothing was compared; the engine must say so rather than imply a negative.',
    ['unresolved', 'candidates', 'empty', 'missing-data'],
    { status: 'unresolved', method: 'unresolved' },
    {
      target: artifactOf('k-c031', 'git:commit', [textFile('src/alone.ts', ['export const alone = true;'])]),
      candidates: [],
    },
  ),
  candidatesCase(
    'c032-candidate-set-single-clear-structural',
    'Single-candidate set with a clean structural match',
    'Even a single candidate through the candidates surface is attribution-conflicted by construction; the engine withholds selection instead of upgrading to structural.',
    ['unresolved', 'candidates', 'same-path', 'clean-capture'],
    { status: 'unresolved', method: 'unresolved' },
    {
      target: artifactOf('k-c032', 'git:commit', [textFile('src/solo.ts', ['export const solo = 1;'])]),
      candidates: [
        { source: artifactOf('p-c032', 'proxy:model-a', [textFile('src/solo.ts', ['export const solo = 1;'])]), temporal: withinWindow() },
      ],
    },
  ),
]);

export const CONTRIBUTION_CORPUS: readonly ContributionCorpusCase[] = deepFreeze([
  ...CORE_CORPUS,
  ...(['semantic_rewrite', 'generated_without_lineage', 'multiple_ai_sources'] as const).map((confounder) => assessPair(
    `confounder-${confounder}`, 'Declared confounder blocks text association',
    'Even identical same-path text is not sufficient when its collector declares a confounder.',
    ['confounder', 'unresolved'], { status: 'unresolved', method: 'unresolved' },
    { ...artifactOf(`proposal-${confounder}`, 'proxy:model-a', [textFile('src/item.ts', ['item();'])]), confounders: [confounder] },
    artifactOf(`target-${confounder}`, 'git:commit', [textFile('src/item.ts', ['item();'])]),
  )),
  ...([0, 9_999, 10_000] as const).map((time) => assessPair(
    `window-end-${time}`, 'Half-open window and strict order',
    'Source at window start is included; simultaneous observations and target at the exclusive end do not establish temporal association.',
    ['temporal', 'boundary'],
    time === 9_999 ? { status: 'temporal', method: 'temporal_association' } : { status: 'unresolved', method: 'unresolved' },
    artifactOf(`p-time-${time}`, 'proxy:model-a', [opaqueFile('asset.bin', 'binary')]),
    artifactOf(`t-time-${time}`, 'git:commit', [opaqueFile('asset.bin', 'binary')]),
    { sourceObservedAtMs: BASE_MS, targetObservedAtMs: BASE_MS + time, windowStartMs: BASE_MS, windowEndMs: BASE_MS + 10_000 },
  )),
  assessPair('null-path', 'Canonical missing path', 'A null path cannot be inferred from matching text.',
    ['pathless', 'missing-data'], { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-null', 'proxy:model-a', [textFile('unused', ['item();'], { path: null })]),
    artifactOf('t-null', 'git:commit', [textFile('src/item.ts', ['item();'])])),
  assessPair('language-mismatch', 'Same fingerprint in different languages', 'Fingerprint equality alone cannot bridge a language mismatch.',
    ['ast', 'boundary'], { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-language', 'proxy:model-a', [textFile('src/item', ['one()'], { language: 'python', structuralFingerprint: 'shape' })]),
    artifactOf('t-language', 'git:commit', [textFile('src/item', ['two();'], { language: 'typescript', structuralFingerprint: 'shape' })])),
  assessPair('line-bound', 'One character beyond comparison limit', 'Oversized text is withheld, never silently truncated into a match.',
    ['boundary', 'partial-capture'], { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-bound', 'proxy:model-a', [textFile('src/item', ['x'.repeat(16_385)])]),
    artifactOf('t-bound', 'git:commit', [textFile('src/item', ['x'.repeat(16_385)])])),
  assessPair('retention-deleted-target', 'Target evidence removed', 'Removing all target evidence leaves association unknown, not refuted.',
    ['retention', 'evidence-removal'], { status: 'unresolved', method: 'unresolved' },
    artifactOf('p-retained', 'proxy:model-a', [textFile('src/item', ['item();'])]),
    artifactOf('t-removed', 'git:commit', [])),
]);

export const CONTRIBUTION_CORPUS_DIGEST_ALGORITHM = 'sha256';

export function corpusStats(cases: readonly ContributionCorpusCase[]): {
  readonly total: number;
  readonly byStatus: Readonly<Record<string, number>>;
  readonly byMethod: Readonly<Record<string, number>>;
} {
  const byStatus: Record<string, number> = {};
  const byMethod: Record<string, number> = {};
  for (const entry of cases) {
    byStatus[entry.expected.status] = (byStatus[entry.expected.status] ?? 0) + 1;
    byMethod[entry.expected.method] = (byMethod[entry.expected.method] ?? 0) + 1;
  }
  return { total: cases.length, byStatus, byMethod };
}
